#!/usr/bin/sh

sxhkd -c /home/maelstrom/.config/sxkhd/sxhkdrc &

xscreensaver -no-splash &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         4
bspc config window_gap          15

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Eyedropper state=floating
bspc rule -a Main.py state=floating

bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

lxpolkit &
killall flameshot
flameshot &
nitrogen --restore &
picom &
~/.config/polybar/./launch.sh &
